### ISSUE TITLE
로고 디자인을 새로 해봤는데 확인부탁드립니다.

### ISSUE THREAD

**Issue by PIut0** [PIut0/ERICA_Cheda#1]
기존 로고를 실제로 적용해보니 살짝 부족한느낌이 들어서
새로 디자인을 해보았습니다.
확인하고 어느쪽이 더 나은지 의견 부탁드립니다.

**Comment by HyeseonLee** [comment]
resolves한 커밋의 mainpage_sp_1115.png파일 확인 부탁드립니다.
