### ISSUE TITLE
Need form info page

### ISSUE THREAD

**Issue by PIut0** [PIut0/ERICA_Cheda#4]
체험들을 나열할 리스트에 어떠한 요소들이 들어가야 하는지 상의가 필요할것 같습니다.
구체적인 필요부분은
1. 리스트 형식일때 간결하게 표현할 요소들.
2. 상세 정보를 누르면 표현할 요소들.
이 부분을 정확히 정해야 할 것 같습니다.

**Comment by HyeseonLee** [comment]
1. 강좌명 | 수강요일 | 교육기간
2. 강좌명
강좌분야
교육대상
교육기간
교육장소
수강요일
접수기간
정원(예비)
접수방법
문의전화

+강좌신청 버튼

이렇게 생각해보았습니다!
