### ISSUE TITLE
suggest combine front-end & back-end

### ISSUE THREAD

**Issue by HyeseonLee** [PIut0/ERICA_Cheda#5]
[기관 별 간략한 프로그램 리스트를 보여줄 페이지]
의 예시로 낙성대동주민센터 페이지 하나를 만들었습니다.

DB를 구축하고, 데이터를 출력까지 하였습니다.

**Comment by HyeseonLee** [comment]
cheda/django_project/chedaapp/templates/nak.html 에 작업하신 프론트 부분을 합치실 수 있습니다.
* CSS, js 코드는 아래와 같은 구조로 폴더를 만들어 담아주시길 바랍니다 :)
* templates
|-------- css
|--------  js
|-------- nak.html

**Comment by HyeseonLee** [comment]
수정합니다. 

- static
    |--------- css
    |--------- font
    |--------- img
    |--------- js
- templates
    |--------- #.html

이렇게 해주세요!

**Comment by PIut0** [comment]
확인했습니다. 먼저 남은 프론트엔드 작업을 모두 마친 후
최종적으로 수정사항이 모두 완료되었을 경우 이후에 백엔드 개발부분과 병합하겠습니다.
그 전까지 DB개발 부탁드립니다

**Comment by HyeseonLee** [comment]
확인했습니다!
