### ISSUE TITLE
DB data language fix

### ISSUE THREAD

**Issue by PIut0** [PIut0/ERICA_Cheda#7]
영어로 된 데이터들을 (기간, 접수기간, 분야)
한글로 바꿔서 데이터를 입력해주세요

**Comment by HyeseonLee** [comment]
기간 
: 2019년 12월 8일 ~ 12월 10일

이런 형식으로 바꾸었습니다!

**Comment by HyeseonLee** [comment]
접수기간
: 2019년 12월 8일 09:00 ~ 12월 10일 18:00

형식으로 바꾸었습니다!

**Comment by HyeseonLee** [comment]
혹시 기간, 접수기간 출력포맷 다른 형식 원하시면 이야기해주세요!
