### ISSUE TITLE
기관별 명칭,변수명 통일

### ISSUE THREAD

**Issue by PIut0** [PIut0/ERICA_Cheda#8]
각 기관의 변수명, 데이터 레이블, 파일네임 등을 통일해야 할것 같습니다.
각 센터별 약칭은 아래와 같이 지칭하겠습니다
싱글벙글 교육센터 : sb
평생학습관 : forever
낙성대동 주민센터 : nak
서울대학교 : snu
미림여자 정보고등학교 : mirim
관악 구민센터 : gumin

**Comment by HyeseonLee** [comment]
확인했습니다!
